### ISSUE TITLE
Data binding

### ISSUE THREAD

**Issue by ghost** [namiwang/flutter_html_widget#1]
There is a graphql project for dart and it does not require the types to be coded in the flutter client.

You just have to use xoaths into the JSON to pluck values.

One the databinding has happened to the html you have normal html and so can feed the html straight into you plugin 

Just asking in case you want to get a PR or I should fork. It seems you only want static Wikipedia style html to be fed in to your plugin .

Anyway let me know

**Comment by namiwang** [comment]
Hi!

This plugin is just trying to do some simple converting like `<p> -> Text`.

I'm not sure I understand your issue completely, but I think that's much more complicated than the intention of this plugin.

So I'd go for a fork. But before that, you should check out

https://github.com/PonnamKarthik/FlutterHtmlView

which seems more features-completed.

**Comment by ghost** [comment]
Thanks I will have a look
