### ISSUE TITLE
SDK constraint ">=2.0.0 <=3.0.0" should be ">=2.0.0 <3.0.0"

### ISSUE THREAD

**Issue by sortie** [namiwang/flutter_html_widget#2]
Hi,

There's an off by one bug in the SDK constraint ">=2.0.0 <=3.0.0", which should be ">=2.0.0 <3.0.0". The goal is to allow all Dart 2 releases, but not Dart 3. The current SDK constraint allows the Dart 3.0.0 release (which would be a future incompatible change that we can't possibly know yet would work with this package),  but not Dart 3.0.1 and up. Please fix the constraint and publish a fixed package.

**Comment by namiwang** [comment]
@sortie Yep, that's definitely not correct. 

But honestly, this package is currently unmaintained.

I strongly recommend you check out https://github.com/PonnamKarthik/FlutterHtmlView as an alternative. 

Unless you're actually focusing on parsing content from wikipedia-api specifically, in that case, ping me!

Thanks again!

**Comment by sortie** [comment]
Hi,

Your package showed up in our internal monitoring of unusual SDK constraints. You can do a quick patch build release that fixes the SDK constraint and helps us move towards the latest version of all packages having correct constraints.

If you're not working on this package anymore, I can mark the package as discontinued, where it still would be available, but the page will show it is discontinued and not encourage people to use it. Please let me know if you would like me to do that (we can always mark it as re-continued should you pick it up again). If you just aren't working on it for the time being, it's fine not to do anything of course.

Jonas

**Comment by namiwang** [comment]
Hi. I've fixed the constraint and uploaded a new version. It's good to know you guys are monitoring this kinda stuff.

**Comment by sortie** [comment]
Thanks, yep, trying to get pub packages better. You may want to update your lower constraint to allow 2.0.0-dev.63.0.flutter-4c9689c1d2, which is currently the version of flutter (not yet on Dart 2 stable) that we use to analyze flutter packages with (but that's not so bad and will eventually fix itself).
